version: "3.5"
services:
    person_count_kitchen:
        build:
            context: ./PersonCountKitchen
        networks:
            - edgehub_public
            - edgehub_tenant_apps
            - proxy_network

    person_count_city:
        build:
            context: ./PersonCount
        networks:
            - edgehub_public
            - edgehub_tenant_apps
            - proxy_network

    fire_detector:
        build:
            context: ./FireDetector
        networks:
            - edgehub_public
            - edgehub_tenant_apps
            - proxy_network

    http_test:
        build:
            context: ./HttpTest
        networks:
            - edgehub_public
            - edgehub_tenant_apps
            - proxy_network


networks:
    edgehub_tenant_apps:
        external: true
    proxy_network:
        external: true
    edgehub_public:
        external: true
