version: "3.5"
services:
    person_count:
        build:
            context: ./PersonCount
        networks:
            - edgehub_tenant_apps
            - proxy_network
            - edgehub_public
        deploy: 
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M
    http_test:
        build:
            context: ./HttpTest
        networks:
            - edgehub_tenant_apps
            - proxy_network
        deploy: 
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M

networks:
    edgehub_tenant_apps:
        external: true
    proxy_network:
        external: true
    edgehub_public:
        external: true
