version: "3.5"
services:
    person_count:
        build:
            context: ./PersonCount
        networks:
            - edgehub_tenant_apps
            - proxy_network

networks:
    edgehub_tenant_apps:
        external: true
    proxy_network:
        external: true
