version: "3.5"
services:
    test_container:
        build:
            context: ./test
        networks:
            - edgehub_tenant_apps
            - proxy_network

networks:
    edgehub_tenant_apps:
        external: true
    proxy_network:
        external: true
