# version: "2"

services:
    zookeeper:
        image: docker.io/bitnami/zookeeper:3.7
        networks:
            - kafka
        ports:
            - "2181:2181"
        volumes:
            - "zookeeper_data:/bitnami"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: docker.io/bitnami/kafka:3
        networks:
            - cloud
            - kafka
        ports:
            - "9092:9092"
        tmpfs: "/datalog" # hack to expire brokers, should not be used in production
        volumes:
            - "kafka_data:/bitnami"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE= true
        depends_on:
            - zookeeper

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local

networks:
    kafka:
        external: false
