version: "3.5"
services:

  # tenant_1:
  #   build:
  #     context: ./Tenant1-Publisher/Surveillance-Camera
  #   networks:
  #     - default

  tenant_2:
    build:
      context: ./Tenant2-AI/AnalyzeVideo
    networks:
      - default

  tenant_web:
    build:
      context: ./Tenant-Web

    ports:
      - "30000:3000"
    networks:
      - default

