version: "3.5"
services:
    # tenant_1:
    #   build:
    #     context: ./Tenant1-Publisher/Surveillance-Camera
    #   networks:
    #     - default

    tenant_2:
        build:
            context: ./Tenant2-AI/AnalyzeVideo
        networks:
            - edgehub_public

    tenant_web:
        build:
            context: ./Tenant-Web
        ports:
            - "30000:3000"
        networks:
            - edgehub_public

networks:
    edgehub_public:
        external: true
